#include "ABGrenadeProjectile.h"
#include "Kismet/GameplayStatics.h"
#include "NiagaraComponent.h"
#include "NiagaraFunctionLibrary.h"
#include "TimerManager.h"

AABGrenadeProjectile::AABGrenadeProjectile()
{
    PrimaryActorTick.bCanEverTick = false;
    // ë©”ì‹œ ì¶”ê°€ (ìˆ˜ë¥˜íƒ„ ëª¨ë¸)
    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("GrenadeMesh"));
    RootComponent = MeshComponent;
    
    MeshComponent->SetHiddenInGame(false);
    MeshComponent->SetVisibility(true);  // ë©”ì‹œ ë³´ì´ë„ë¡ ì„¤ì •
    // ì¶©ëŒ ì»´í¬ë„ŒíŠ¸ ìƒì„±
    CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionComponent"));
    CollisionComponent->InitSphereRadius(5.0f);  // ì¶©ëŒ ë²”ìœ„ ì„¤ì •
    CollisionComponent->SetCollisionProfileName(TEXT("BlockAllDynamic"));
    CollisionComponent->SetNotifyRigidBodyCollision(true);
    CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);  // ì¶©ëŒ í™œì„±í™”
    CollisionComponent->SetCollisionObjectType(ECC_PhysicsBody);  // ë¬¼ë¦¬ ë°”ë””ë¡œ ì„¤ì •
    CollisionComponent->SetCollisionResponseToAllChannels(ECR_Block);  // ëª¨ë“  ì˜¤ë¸Œì íŠ¸ì™€ ì¶©ëŒ
    // ë£¨íŠ¸ ì»´í¬ë„ŒíŠ¸ ì„¤ì •
    CollisionComponent->SetupAttachment(MeshComponent);
    
    // ğŸ”¹ ìºë¦­í„°(Pawn)ì™€ ì¶©ëŒ ë¬´ì‹œ
    CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Ignore);

    // ğŸ”¹ ì†Œìœ ìì™€ ì¶©ëŒ ë°©ì§€
    if (GetOwner())
    {
        CollisionComponent->IgnoreActorWhenMoving(GetOwner(), true);
    }

    // OnHit ì´ë²¤íŠ¸ ë°”ì¸ë”©
    if (CollisionComponent)
    {
        CollisionComponent->OnComponentHit.AddDynamic(this, &AABGrenadeProjectile::OnHit);
    }

    // ë¬¼ë¦¬ ì‹œë®¬ë ˆì´ì…˜ í™œì„±í™”
    MeshComponent->SetCollisionObjectType(ECC_PhysicsBody); // ë˜ëŠ” ECC_WorldDynamic
    MeshComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);
    MeshComponent->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Block);
    MeshComponent->SetCollisionResponseToChannel(ECC_WorldDynamic, ECR_Block);


    // ë°œì‚¬ì²´ ì´ë™ ì»´í¬ë„ŒíŠ¸ ì¶”ê°€
    ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovement"));
    ProjectileMovement->UpdatedComponent = CollisionComponent;
    ProjectileMovement->InitialSpeed = 1000.0f;  // ì´ˆê¸° ì†ë„
    ProjectileMovement->MaxSpeed = 1000.0f;
    ProjectileMovement->bRotationFollowsVelocity = true;
    ProjectileMovement->bShouldBounce = true;  // íŠ•ê¸°ëŠ” ê¸°ëŠ¥ í™œì„±í™”
    ProjectileMovement->Bounciness = 0.0f;     // ë°”ìš´ìŠ¤ ê°•ë„ (0~1)
    ProjectileMovement->Friction = 0.2f;       // ë§ˆì°°ë ¥ (0~1)
    ProjectileMovement->bBounceAngleAffectsFriction = true; // ê°ë„ì— ë”°ë¼ ë§ˆì°° ì ìš©

    // ì¼ì • ì‹œê°„ì´ ì§€ë‚˜ë©´ í­ë°œí•˜ë„ë¡ ì„¤ì •
    InitialLifeSpan = ExplosionDelay;
}

void AABGrenadeProjectile::FireInDirection(const FVector& ShootDirection)
{
    if (ProjectileMovement)
    {
        ProjectileMovement->Velocity = ShootDirection * ProjectileMovement->InitialSpeed;
    }
}

void AABGrenadeProjectile::BeginPlay()
{
    Super::BeginPlay();

    if (MeshComponent)
    {
        MeshComponent->OnComponentHit.AddDynamic(this, &AABGrenadeProjectile::OnHit);
        UE_LOG(LogTemp, Warning, TEXT("âœ… OnHit successfully bound!"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ MeshComponent is NULL in BeginPlay!"));
    }
    // ì¶©ëŒ í›„ 3ì´ˆ ë’¤ì— í­ë°œ í•¨ìˆ˜ í˜¸ì¶œ
    GetWorld()->GetTimerManager().SetTimer(ExplosionTimerHandle, this, &AABGrenadeProjectile::Explode, 3.0f, false);
}
void AABGrenadeProjectile::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit)
{
    // ì¶©ëŒ ì‹œ ë¡œê·¸ ì¶œë ¥
    UE_LOG(LogTemp, Warning, TEXT("âš¡ Grenade Hit: %s"), *Hit.GetActor()->GetName());
}
void AABGrenadeProjectile::Explode()
{
    // í­ë°œ ìœ„ì¹˜ê°€ (0,0,0)ì¸ì§€ë¥¼ í™•ì¸í•˜ê³ , ì ì ˆíˆ ì„¤ì •
    if (ExplosionLocation.IsNearlyZero())
    {
        ExplosionLocation = GetActorLocation(); // í˜„ì¬ ì•¡í„° ìœ„ì¹˜ë¥¼ ì‚¬ìš©
    }

    UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ Explosion at: X=%.2f Y=%.2f Z=%.2f"),
        ExplosionLocation.X, ExplosionLocation.Y, ExplosionLocation.Z);

    // í­ë°œ ì´í™íŠ¸ ë° ë°ë¯¸ì§€ ì ìš© (ê¸°ì¡´ ì½”ë“œ)
    if (ExplosionEffect)
    {
        UNiagaraComponent* NiagaraEffect = UNiagaraFunctionLibrary::SpawnSystemAtLocation(
            GetWorld(), ExplosionEffect, ExplosionLocation, FRotator::ZeroRotator);

        if (NiagaraEffect)
        {
            // ì¼ì • ì‹œê°„ í›„ í­ë°œ ì´í™íŠ¸ ì œê±°
            FTimerHandle TimerHandle;
            GetWorld()->GetTimerManager().SetTimer(TimerHandle, [NiagaraEffect]() {
                NiagaraEffect->DestroyComponent();
                }, 3.0f, false);
        }
    }

    // í­ë°œ ë°ë¯¸ì§€ ì ìš©
    UGameplayStatics::ApplyRadialDamage(
        GetWorld(), ExplosionDamage, ExplosionLocation, ExplosionRadius,
        UDamageType::StaticClass(), TArray<AActor*>(), this, GetInstigatorController(), true);

    // ì•¡í„° ì œê±°
    Destroy();
}
