#include "BCharacter.h"
#include "BPlayerController.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Camera/CameraComponent.h"
#include "Kismet/GameplayStatics.h"
#include "EnhancedInputComponent.h"
#include "BMovementComponent.h"
#include "Components/SphereComponent.h"
#include "BBaseItem.h"
#include "BBaseGun.h"
#include "BRiflePart.h"
#include "BPistolPart.h"
#include "BShotgunPart.h"
#include "BPlayerState.h"
#include "BUIManager.h"
#include "BGameInstance.h"
#include "BInventoryWidget.h"



ABCharacter::ABCharacter(const FObjectInitializer& ObjectInitializer)
{
	PrimaryActorTick.bCanEverTick = false;
	ActiveWeaponSlot = EWeaponSlot::Pistol;  // ÃªÂ¸Â°Ã«Â³Â¸Ã¬Â ÂÃ¬Å“Â¼Ã«Â¡Å“ Ã¬Â£Â¼Ã«Â¬Â´ÃªÂ¸Â°Ã«Â¥Â¼ Ã­â„¢Å“Ã¬â€Â±Ã­â„¢â€
	// Ã«Â°Â°Ã¬â€”Â´Ã¬ÂËœ Ã­ÂÂ¬ÃªÂ¸Â°Ã«Â¥Â¼ ActiveWeaponSlotÃ¬â€”Â Ã«Â§Å¾ÃªÂ²Å’ Ã­â„¢â€¢Ã¬Å¾Â¥
	EquippedWeapons.SetNumZeroed(5);  // ActiveWeaponSlotÃ¬â€”Â Ã«Â§Å¾ÃªÂ²Å’ Ã«Â°Â°Ã¬â€”Â´ Ã­ÂÂ¬ÃªÂ¸Â° Ã¬â€Â¤Ã¬Â â€¢
	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->TargetArmLength = 300.f;
	SpringArm->bUsePawnControlRotation = true; // ?Å’Ã¬Â â€??Ã¬Â¹Â´Ã«Â©â€?Â¼Ã«Ââ€ ?Â´Ã«Ââ„¢?Å“Ã«â€¹Â¤.
	SpringArm->SetupAttachment(GetRootComponent());

	CameraComp = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	CameraComp->SetupAttachment(SpringArm);
	CameraComp->bUsePawnControlRotation = false; // Ã¬Â¹Â´Ã«Â©â€?Â¼Ã«Ââ€ ?Å’Ã¬Â â€?ËœÃ«Â©Â´ ?â€¢Ã¬â€¹Â ?â€ Ã¬Å“Â¼Ã«Â¯â‚¬Ã«Â¡?false

	Collision = GetCapsuleComponent();
	check(Collision);
	Skeletal = GetMesh();
	check(Skeletal);
	MoveComp = CastChecked<UBMovementComponent>(GetCharacterMovement());
	check(MoveComp);
	MoveComp->GravityScale = 1.f;
	MoveComp->MaxAcceleration = 2400.0f;
	MoveComp->BrakingFrictionFactor = 1.0f;
	MoveComp->BrakingFriction = 6.0f;
	MoveComp->GroundFriction = 8.0f;
	MoveComp->BrakingDecelerationWalking = 1400.0f;
	MoveComp->bUseControllerDesiredRotation = false;
	MoveComp->bOrientRotationToMovement = false;
	MoveComp->RotationRate = FRotator(0.0f, 720.0f, 0.0f);
	MoveComp->bAllowPhysicsRotationDuringAnimRootMotion = false;
	MoveComp->GetNavAgentPropertiesRef().bCanCrouch = true;
	MoveComp->bCanWalkOffLedgesWhenCrouching = true;
	MoveComp->SetCrouchedHalfHeight(65.0f);

	CollectNearItem = CreateDefaultSubobject<USphereComponent>(TEXT("SphereComponent"));
	CollectNearItem->SetupAttachment(GetRootComponent());
	CollectNearItem->SetSphereRadius(400.f);
}

ABPlayerState* ABCharacter::GetBPlayerState() const
{
	return CastChecked<ABPlayerState>(GetPlayerState(), ECastCheckedType::NullAllowed);
}

ABPlayerController* ABCharacter::GetBPlayerController() const
{
	return CastChecked<ABPlayerController>(Controller, ECastCheckedType::NullAllowed);
}

FVector ABCharacter::GetCameraForwardVector() const
{
	if (CameraComp)
	{
		return CameraComp->GetForwardVector();
	}

	return GetActorForwardVector();  // Ã¬Â¹Â´Ã«Â©â€Ã«ÂÂ¼ÃªÂ°â‚¬ Ã¬â€”â€ Ã¬Å“Â¼Ã«Â©Â´ ÃªÂ¸Â°Ã«Â³Â¸ Ã«Â°Â©Ã­â€“Â¥ Ã«Â°ËœÃ­â„¢Ëœ
}

void ABCharacter::Move(const FInputActionValue& Value)
{
	if (!Controller) return;

	FVector2D MoveInput = Value.Get<FVector2D>();

	if (!FMath::IsNearlyZero(MoveInput.X))
	{
		AddMovementInput(GetActorForwardVector(), MoveInput.X);
	}
	if (!FMath::IsNearlyZero(MoveInput.Y))
	{
		AddMovementInput(GetActorRightVector(), MoveInput.Y);
	}
}

void ABCharacter::Look(const FInputActionValue& Value)
{
	const FVector2D LookInput = Value.Get<FVector2D>();
	AddControllerYawInput(LookInput.X);
	AddControllerPitchInput(LookInput.Y);
}

void ABCharacter::StartJump(const FInputActionValue& Value)
{
	if (Value.Get<bool>())
	{
		Jump();
	}
}

void ABCharacter::StopJump(const FInputActionValue& Value)
{
	if (!Value.Get<bool>())
	{
		StopJumping();
	}
}

void ABCharacter::StartSprint(const FInputActionValue& Value)
{
	if (Value.Get<bool>())
	{
		// PlayerStateÃ«Â¥?ÃªÂ°â‚¬?Â¸Ã¬???Ã¬Â²ËœÃ«Â¦Â¬?ËœÃ«Ââ€Ã«Â¡??ËœÃ¬Å¾Â.
		// TODO : GetCharacterMovement()->MaxWalkSpeed = SprintSpeed;
	}
}

void ABCharacter::StopSprint(const FInputActionValue& Value)
{
	if (!Value.Get<bool>())
	{
		// PlayerStateÃ«Â¥?ÃªÂ°â‚¬?Â¸Ã¬???Ã¬Â²ËœÃ«Â¦Â¬?ËœÃ«Ââ€Ã«Â¡??ËœÃ¬Å¾Â.
		// TODO : GetCharacterMovement()->MaxWalkSpeed = NomalSpeed;
	}
}

void ABCharacter::Reload(const FInputActionValue& Value)
{
	if (!EquippedWeapon)
	{
		UE_LOG(LogTemp, Warning, TEXT("ì¥ì°©ëœ ë¬´ê¸°ê°€ ì—†ìŠµë‹ˆë‹¤. ë¦¬ë¡œë“œ ì‹¤íŒ¨."));
		return;
	}

	if (ABBaseGun* CurrentGun = Cast<ABBaseGun>(EquippedWeapon))
	{
		// íƒ„ì°½ì´ í•„ìš”í•œ ë¬´ê¸°ì¼ ê²½ìš° (ì˜ˆ: ë¼ì´í”Œ, ìƒ·ê±´ ë“±)
		if (CurrentGun->WeaponType == "Rifle")
		{
			// ë¦¬ë¡œë“œ ì‹œì‘
			UE_LOG(LogTemp, Log, TEXT("ë¼ì´í”Œ ë¦¬ë¡œë“œ ì¤‘..."));

				if (ABPlayerState* BPlayerState = GetBPlayerState())
				{
					FName RifleMagazine = "RifleMagazine";
					// ë¬´ê¸°ì˜ ì¢…ë¥˜ì— ë§ëŠ” íƒ„ì•½ ì•„ì´í…œì„ ì¸ë²¤í† ë¦¬ì—ì„œ ì°¾ìŒ
					TArray<FItemData> AmmoItems = BPlayerState->GetInventoryTypeItem(RifleMagazine);
					if (AmmoItems.Num() > 0)
					{
						// ì•„ì´í…œì´ ìˆë‹¤ë©´ ì²« ë²ˆì§¸ ì•„ì´í…œì„ ì‚¬ìš©í•˜ì—¬ ë¦¬ë¡œë“œ
						ABBaseItem* AmmoItem = AmmoItems[0].ItemRef;  // FItemData ë‚´ì—ì„œ ItemRefë¥¼ í†µí•´ ì¸ìŠ¤í„´ìŠ¤ ê°€ì ¸ì˜¤ê¸°
						if (AmmoItem)
						{
							AmmoItem->UseItem(this);  // UseItemì„ í˜¸ì¶œí•˜ì—¬ ë¦¬ë¡œë“œ ì‹¤í–‰
							UE_LOG(LogTemp, Log, TEXT("ë¦¬ë¡œë“œ ì•„ì´í…œì„ ì‚¬ìš©í•˜ì—¬ íƒ„ì•½ ì¶”ê°€"));
							// UseItemì´ ëë‚œ í›„ ë¦¬ë¡œë“œë¥¼ í˜¸ì¶œí•˜ì—¬ ì´ê¸°ì˜ íƒ„ì•½ ìƒíƒœ ì—…ë°ì´íŠ¸
							CurrentGun->Reload(); // ë¦¬ë¡œë“œ í•¨ìˆ˜ í˜¸ì¶œí•˜ì—¬ ì‹¤ì œ ì´ê¸°ì˜ CurrentAmmo ì¦ê°€
						}
					}
					else
					{
						UE_LOG(LogTemp, Warning, TEXT("ë¦¬ë¡œë“œ ì•„ì´í…œì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
					}
				}
		}
		// íƒ„ì°½ì´ í•„ìš”í•œ ë¬´ê¸°ì¼ ê²½ìš° (ì˜ˆ: ë¼ì´í”Œ, ìƒ·ê±´ ë“±)
		else if (CurrentGun->WeaponType == "ShotGun")
		{
			// ë¦¬ë¡œë“œ ì‹œì‘
			UE_LOG(LogTemp, Log, TEXT("ìƒ·ê±´ ë¦¬ë¡œë“œ ì¤‘..."));

			if (ABPlayerState* BPlayerState = GetBPlayerState())
				{
					FName ShotGunMagazine = "ShotgunMagazine";
					// ë¬´ê¸°ì˜ ì¢…ë¥˜ì— ë§ëŠ” íƒ„ì•½ ì•„ì´í…œì„ ì¸ë²¤í† ë¦¬ì—ì„œ ì°¾ìŒ
					TArray<FItemData> AmmoItems = BPlayerState->GetInventoryTypeItem(ShotGunMagazine);
					if (AmmoItems.Num() > 0)
					{
						// ì•„ì´í…œì´ ìˆë‹¤ë©´ ì²« ë²ˆì§¸ ì•„ì´í…œì„ ì‚¬ìš©í•˜ì—¬ ë¦¬ë¡œë“œ
						ABBaseItem* AmmoItem = AmmoItems[0].ItemRef;  // FItemData ë‚´ì—ì„œ ItemRefë¥¼ í†µí•´ ì¸ìŠ¤í„´ìŠ¤ ê°€ì ¸ì˜¤ê¸°
						if (AmmoItem)
						{
							AmmoItem->UseItem(this);  // UseItemì„ í˜¸ì¶œí•˜ì—¬ ë¦¬ë¡œë“œ ì‹¤í–‰
							UE_LOG(LogTemp, Log, TEXT("ë¦¬ë¡œë“œ ì•„ì´í…œì„ ì‚¬ìš©í•˜ì—¬ íƒ„ì•½ ì¶”ê°€"));
							// UseItemì´ ëë‚œ í›„ ë¦¬ë¡œë“œë¥¼ í˜¸ì¶œí•˜ì—¬ ì´ê¸°ì˜ íƒ„ì•½ ìƒíƒœ ì—…ë°ì´íŠ¸
							CurrentGun->Reload(); // ë¦¬ë¡œë“œ í•¨ìˆ˜ í˜¸ì¶œí•˜ì—¬ ì‹¤ì œ ì´ê¸°ì˜ CurrentAmmo ì¦ê°€
						}
					}
					else
					{
						UE_LOG(LogTemp, Warning, TEXT("ë¦¬ë¡œë“œ ì•„ì´í…œì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
					}
				}
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("ë¦¬ë¡œë“œí•  ìˆ˜ ì—†ëŠ” ë¬´ê¸°ì…ë‹ˆë‹¤."));
		}
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("í˜„ì¬ ì¥ì°©ëœ ë¬´ê¸°ê°€ ì´ê¸°ê°€ ì•„ë‹™ë‹ˆë‹¤."));
	}
}


void ABCharacter::ZoomStart(const FInputActionValue& Value)
{
	if (CameraComp)
	{
		CameraComp->SetFieldOfView(ZoomedFOV); // ì¤Œ ìƒíƒœ (ì˜ˆ: 45.0f)
	}
}

void ABCharacter::ZoomStop(const FInputActionValue& Value)
{
	if (CameraComp)
	{
		CameraComp->SetFieldOfView(DefaultFOV); // ì›ë˜ ìƒíƒœ (ì˜ˆ: 90.0f)
	}
}

void ABCharacter::BeginPlay()
{
	Super::BeginPlay();

	State = Cast<ABPlayerState>(GetPlayerState());
}
void ABCharacter::Attack(const struct FInputActionValue& Value)
{
	UE_LOG(LogTemp, Log, TEXT("Attack() called"));
	if (EquippedWeapon == nullptr)
	{
		return;
	}
	UE_LOG(LogTemp, Warning, TEXT("âš”ï¸ ê³µê²© ì‹œì‘: %s"), *EquippedWeapon->GetName());

	// ğŸ”¹ ìœ íš¨í•œ ìŠ¬ë¡¯ì¸ì§€ í™•ì¸
	if (!EquippedWeapons.IsValidIndex((int32)ActiveWeaponSlot))
	{
		UE_LOG(LogTemp, Warning, TEXT("Invalid ActiveWeaponSlot: %d"), (int32)ActiveWeaponSlot);
		return;
	}

	// ğŸ”¹ í˜„ì¬ ìŠ¬ë¡¯ì˜ ë¬´ê¸° ê°€ì ¸ì˜¤ê¸°
	ABBaseWeapon* CurrentWeapon = EquippedWeapons[(int32)ActiveWeaponSlot];
	if (!CurrentWeapon)
	{
		UE_LOG(LogTemp, Warning, TEXT("No weapon equipped in slot: %d"), (int32)ActiveWeaponSlot);
		return;
	}
	if (CurrentWeapon->WeaponType == "Grenade" && GrenadeCount <= 0) 
	{
		UE_LOG(LogTemp, Log, TEXT("ğŸ’£ ìˆ˜ë¥˜íƒ„ ì¥ì°© í•´ì œ ì™„ë£Œ!"));
		UnequipGrenade();
		return;
	}
	UE_LOG(LogTemp, Warning, TEXT("ğŸ” [FireOnce] í˜„ì¬ ë¬´ê¸° íƒ€ì…: %s"), *CurrentWeapon->WeaponType);

	CurrentWeapon->Attack();
}
void ABCharacter::UnequipGrenade()
{
	if (EquippedWeapon && EquippedWeapon->WeaponType == "Grenade")
	{
			UE_LOG(LogTemp, Log, TEXT("Hiding previously equipped weapon: %s"), *EquippedWeapon->WeaponType);
			EquippedWeapon->SetActorHiddenInGame(true);
			EquippedWeapon->SetActorEnableCollision(false);
			EquippedWeapon->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);

			// ë¬´ê¸° ë³´ê´€ ìœ„ì¹˜ ì„¤ì •
			FName StorageSocketName = TEXT("WeaponStorageSocket");
			if (GetMesh()->DoesSocketExist(StorageSocketName))
			{
				EquippedWeapon->AttachToComponent(GetMesh(), FAttachmentTransformRules::SnapToTargetNotIncludingScale, StorageSocketName);
			}
		
		UE_LOG(LogTemp, Log, TEXT("ğŸ’£ ìˆ˜ë¥˜íƒ„ ì¥ì°© í•´ì œ ì™„ë£Œ!"));
	}
}


void ABCharacter::StopFire()
{
	UE_LOG(LogTemp, Log, TEXT("StopFire"));
	// Ã«Â°Å“Ã¬â€šÂ¬ Ã«Â©Ë†Ã¬Â¶â€ÃªÂ¸Â°
	GetWorld()->GetTimerManager().ClearTimer(FireTimerHandle);
}

void ABCharacter::PickupWeapon(ABBaseWeapon* NewWeapon)
{
	if (!NewWeapon)
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Failed to pick up weapon. NewWeapon is null."));
		return;
	}

	// ğŸ”¹ ì´ë¯¸ ì¸ë²¤í† ë¦¬ì— ìˆëŠ”ì§€ í™•ì¸
	for (ABBaseWeapon* ExistingWeapon : EquippedWeapons)
	{
		if (ExistingWeapon == NewWeapon)  // ê°™ì€ ë¬´ê¸°ì¸ì§€ í™•ì¸
		{
			return;  // ì¤‘ë³µ ì¶”ê°€ ë°©ì§€
		}
	}

	// ğŸ”¹ ë¬´ê¸° ë°°ì—´ì— ì¶”ê°€ (ë°°ì—´ í¬ê¸° ì²´í¬)
	if (NewWeapon->WeaponType.Equals("Melee", ESearchCase::IgnoreCase))
	{
		EquippedWeapons[(int32)EWeaponSlot::Melee] = NewWeapon;
	}
	else if (NewWeapon->WeaponType.Equals("Grenade", ESearchCase::IgnoreCase))
	{
		EquippedWeapons[(int32)EWeaponSlot::Throwable] = NewWeapon;
		GrenadeCount++;
	}

	else if (NewWeapon->WeaponType.Equals("Rifle", ESearchCase::IgnoreCase))
	{
		EquippedWeapons[(int32)EWeaponSlot::Rifle] = NewWeapon;
	}
	else if (NewWeapon->WeaponType.Equals("Pistol", ESearchCase::IgnoreCase))
	{
		EquippedWeapons[(int32)EWeaponSlot::Pistol] = NewWeapon;
	}
	else if (NewWeapon->WeaponType.Equals("ShotGun", ESearchCase::IgnoreCase))
	{
		EquippedWeapons[(int32)EWeaponSlot::ShotGun] = NewWeapon;
	}

	// âœ… ì—¬ê¸°ì„œ ë°”ë¡œ WeaponSocketìœ¼ë¡œ ë¶€ì°©í•˜ì§€ ì•ŠìŒ
	FName StorageSocketName = TEXT("WeaponStorageSocket");
	if (GetMesh()->DoesSocketExist(StorageSocketName))
	{
		if (NewWeapon->WeaponType.Equals("Grenade", ESearchCase::IgnoreCase))
		{
			// ìˆ˜ë¥˜íƒ„ì˜ ìŠ¤ì¼€ì¼ì„ ì¤„ì—¬ì„œ ì„¤ì • (ì˜ˆ: 0.5ë°°)
			NewWeapon->SetActorScale3D(FVector(0.05f, 0.05f, 0.05f));

			UE_LOG(LogTemp, Log, TEXT("Grenade picked up. Scale set to 0.05."));
		}
		NewWeapon->AttachToComponent(GetMesh(), FAttachmentTransformRules::SnapToTargetNotIncludingScale, StorageSocketName);
		UE_LOG(LogTemp, Log, TEXT("âœ… Weapon stored in %s"), *StorageSocketName.ToString());
		NewWeapon->SetActorHiddenInGame(true);
	}

	UE_LOG(LogTemp, Log, TEXT("âœ… Picked up WeaponType: %s"), *NewWeapon->WeaponType);
}

ABBaseWeapon* ABCharacter::GetCurrentWeapon() const
{
	return EquippedWeapon;
}



void ABCharacter::EquipWeaponByType(EWeaponSlot Slot)
{
	// ğŸ”¹ ì¸ë±ìŠ¤ê°€ ì˜¬ë°”ë¥¸ì§€ ê²€ì‚¬
	if (!EquippedWeapons.IsValidIndex((int32)Slot))
	{
		UE_LOG(LogTemp, Error, TEXT("EquipWeaponByType: Slot %d is out of bounds! Max size: %d"),
			(int32)Slot, EquippedWeapons.Num());
		return;
	}

	// ğŸ”¹ ë¬´ê¸° ë°°ì—´ í¬ê¸°ê°€ ë¶€ì¡±í•˜ë©´ í™•ì¥
	if (EquippedWeapons.Num() <= (int32)Slot)
	{
		EquippedWeapons.SetNum((int32)Slot + 1);
	}

	// ğŸ”¹ í˜„ì¬ ìŠ¬ë¡¯ ì—…ë°ì´íŠ¸
	ActiveWeaponSlot = Slot;
	ABBaseWeapon* WeaponToEquip = EquippedWeapons[(int32)Slot];

	if (!WeaponToEquip)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ WeaponToEquip is nullptr! Slot: %d"), (int32)Slot);
		return;
	}

	// ğŸ”¹ íƒ€ì´ë¨¸ ì´ˆê¸°í™” (ë°œì‚¬ ë”œë ˆì´ ë¦¬ì…‹)
	GetWorldTimerManager().ClearTimer(FireTimerHandle);

	// ğŸ”¹ ë¬´ê¸° ë©”ì‰¬ í™•ì¸
	UStaticMeshComponent* WeaponMesh = WeaponToEquip->FindComponentByClass<UStaticMeshComponent>();

	// ğŸ”¹ ìˆ˜ë¥˜íƒ„ì¸ë° ê°œìˆ˜ê°€ 0ì´ë©´ ì¥ì°© ì•ˆë˜ê²Œ ì„¤ì •
	if (Slot == EWeaponSlot::Throwable && GrenadeCount <= 0)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ GrenadeCount is 0"));
		WeaponMesh = nullptr;
	}

	// ğŸ”¹ WeaponMeshê°€ nullptrì´ë©´ ê¸°ì¡´ ë¬´ê¸° í•´ì œ
	if (!WeaponMesh)
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ WeaponMesh is nullptr, unequipping current weapon"));
		if (EquippedWeapon)
		{
			EquippedWeapon->SetActorHiddenInGame(true);
			EquippedWeapon->SetActorEnableCollision(false);
			EquippedWeapon->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);
			EquippedWeapon = nullptr;
		}
		return;
	}

	// ğŸ”¹ ê¸°ì¡´ ì¥ì°© ë¬´ê¸° ìˆ¨ê¸°ê¸° + ì¸ë²¤í† ë¦¬ì— ì €ì¥
	if (EquippedWeapon)
	{
		UE_LOG(LogTemp, Log, TEXT("Hiding previously equipped weapon: %s"), *EquippedWeapon->WeaponType);
		EquippedWeapon->SetActorHiddenInGame(true);
		EquippedWeapon->SetActorEnableCollision(false);
		EquippedWeapon->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);

		// ë¬´ê¸° ë³´ê´€ ìœ„ì¹˜ ì„¤ì •
		FName StorageSocketName = TEXT("WeaponStorageSocket");
		if (GetMesh()->DoesSocketExist(StorageSocketName))
		{
			EquippedWeapon->AttachToComponent(GetMesh(), FAttachmentTransformRules::SnapToTargetNotIncludingScale, StorageSocketName);
		}
	}

	// ğŸ”¹ ìƒˆë¡œìš´ ë¬´ê¸° ì¥ì°©
	FName TargetSocketName = TEXT("WeaponSocket");
	if (!GetMesh()->DoesSocketExist(TargetSocketName))
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ Target Socket %s does not exist!"), *TargetSocketName.ToString());
		return;
	}

	// ğŸ”¹ ë¨¼ì € ë¬´ê¸°ë¥¼ ìˆ¨ê¹€ í•´ì œ
	WeaponToEquip->SetActorHiddenInGame(false);
	WeaponToEquip->SetActorEnableCollision(true);
	WeaponToEquip->ForceNetUpdate(); // ë„¤íŠ¸ì›Œí¬ ë™ê¸°í™”

	// ğŸ”¹ AttachToComponent ì‹œë„ ë° ì„±ê³µ ì—¬ë¶€ í™•ì¸
	bool bAttachSuccess = WeaponToEquip->AttachToComponent(GetMesh(),
		FAttachmentTransformRules::SnapToTargetNotIncludingScale, TargetSocketName);

	if (!bAttachSuccess)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ AttachToComponent FAILED for %s!"), *WeaponToEquip->GetName());
		return;
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("âœ… %s attached to %s successfully: %s"), *WeaponToEquip->GetName(), *TargetSocketName.ToString(), *WeaponToEquip -> GetActorLocation().ToString());
	}

	// ğŸ”¹ ë¬´ê¸° ë©”ì‰¬ ì²˜ë¦¬
	if (WeaponMesh)
	{
		WeaponMesh->SetHiddenInGame(false);
		WeaponMesh->SetVisibility(true);
		WeaponMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	}

	// ğŸ”¹ ë¬¼ë¦¬(Physics) ì˜í–¥ ë°©ì§€
	WeaponMesh->SetSimulatePhysics(false);

	// ğŸ”¹ ë¬´ê¸° íšŒì „ê°’ ì¡°ì • (ë¬´ê¸° íƒ€ì…ë³„)
	FRotator AdjustedRotation(0.0f, 0.0f, 0.0f);
	if (WeaponToEquip->WeaponType == "Rifle")
	{
		AdjustedRotation = FRotator(0.0f, -180.0f, 0.0f);
	}
	else if (WeaponToEquip->WeaponType == "Shotgun") 
	{
		AdjustedRotation = FRotator(0.0f, -180.0f, 0.0f);
	}
	else if (WeaponToEquip->WeaponType == "Pistol")
	{
		AdjustedRotation = FRotator(0.0f, 90.0f, 90.0f);
	}
	else if (WeaponToEquip->WeaponType == "Melee")
	{
		AdjustedRotation = FRotator(90.0f, -90.0f, 90.0f);
	}
	else if (WeaponToEquip->WeaponType == "Grenade")
	{
		WeaponToEquip->SetActorRelativeLocation(FVector::ZeroVector);
		AdjustedRotation = FRotator(90.0f, -90.0f, 90.0f); 
	}
	WeaponToEquip->SetActorRelativeRotation(AdjustedRotation);

	// ğŸ”¹ ì¥ì°©ëœ ë¬´ê¸° ì—…ë°ì´íŠ¸
	EquippedWeapon = WeaponToEquip;

	UE_LOG(LogTemp, Warning, TEXT("ğŸ“Œ CurrentWeapon: %s"), *EquippedWeapon->GetName());

	if (EquippedWeapon->WeaponType.Equals("Rifle"))  // Equals() ì‚¬ìš©
	{
		UE_LOG(LogTemp, Warning, TEXT("ë¼ì´í”Œ íŒŒì¸  ì¥ì°©"));
		EquipRifleParts();  // ë¼ì´í”Œ íŒŒì¸  ì¥ì°©
		if (UBGameInstance* Instance = Cast<UBGameInstance>(GetGameInstance()))
		{
			if (UBUIManager* UIManager = Cast<UBUIManager>(Instance->GetUIManagerInstance()))
			{
				if (ABBaseGun* Gun = Cast<ABBaseGun>(EquippedWeapon))
				{
					
					FString Message = TEXT("ë°ë¯¸ì§€: ") + FString::Printf(TEXT("%d"), Gun->WeaponDamage) +
						TEXT(", ë°œì‚¬ì†ë„: ") + FString::Printf(TEXT("%.0f"), Gun->FireRate) +
						TEXT(", ìµœëŒ€ ì¥íƒ„ ìˆ˜: ") + FString::Printf(TEXT("%d"), Gun->MaxAmmo);
					UIManager->DisplayNotification(TEXT("ë¼ì´í”Œ ê°•í™” ì™„ë£Œ"), Message);
				}
				if (UBInventoryWidget* Inventory = Cast<UBInventoryWidget>(UIManager->GetInventoryInstance()))
				{
					Inventory->SendItemData(GetNearItemArray(), Cast<ABPlayerState>(GetPlayerState()));
				}
			}
		}
	}
	else if (EquippedWeapon->WeaponType.Equals("Shotgun"))  // Equals() ì‚¬ìš©
	{
		UE_LOG(LogTemp, Warning, TEXT("ìƒ·ê±´ íŒŒì¸  ì¥ì°©"));
		EquipShotgunParts();  // ë¼ì´í”Œ íŒŒì¸  ì¥ì°©
		if (UBGameInstance* Instance = Cast<UBGameInstance>(GetGameInstance()))
		{
			if (UBUIManager* UIManager = Cast<UBUIManager>(Instance->GetUIManagerInstance()))
			{
				if (ABBaseGun* Gun = Cast<ABBaseGun>(EquippedWeapon))
				{
					FString Message = TEXT("ë°ë¯¸ì§€: ") + FString::Printf(TEXT("%d"), Gun->WeaponDamage) +
						TEXT(", ë°œì‚¬ì†ë„: ") + FString::Printf(TEXT("%.0f"), Gun->FireRate) +
						TEXT(", ìµœëŒ€ ì¥íƒ„ ìˆ˜: ") + FString::Printf(TEXT("%d"), Gun->MaxAmmo);
					UIManager->DisplayNotification(TEXT("ìƒ·ê±´ ê°•í™” ì™„ë£Œ"), Message);
				}
				if (UBInventoryWidget* Inventory = Cast<UBInventoryWidget>(UIManager->GetInventoryInstance()))
				{
					Inventory->SendItemData(GetNearItemArray(), Cast<ABPlayerState>(GetPlayerState()));
				}
			}
		}
	}
	else if (EquippedWeapon->WeaponType.Equals("Pistol"))  // Equals() ì‚¬ìš©
	{
		UE_LOG(LogTemp, Warning, TEXT("í”¼ìŠ¤í†¨ íŒŒì¸  ì¥ì°©"));
		if (UBGameInstance* Instance = Cast<UBGameInstance>(GetGameInstance()))
		{
			if (UBUIManager* UIManager = Cast<UBUIManager>(Instance->GetUIManagerInstance()))
			{
				if (ABBaseGun* Gun = Cast<ABBaseGun>(EquippedWeapon))
				{
					FString Message = TEXT("ë°ë¯¸ì§€: ") + FString::Printf(TEXT("%d"), Gun->WeaponDamage);
					UIManager->DisplayNotification(TEXT("í”¼ìŠ¤í†¨ ê°•í™” ì™„ë£Œ"), Message);
				}
				if (UBInventoryWidget* Inventory = Cast<UBInventoryWidget>(UIManager->GetInventoryInstance()))
				{
					Inventory->SendItemData(GetNearItemArray(), Cast<ABPlayerState>(GetPlayerState()));
				}
			}
		}
		EquipPistolParts();  // ë¼ì´í”Œ íŒŒì¸  ì¥ì°©
	}
}
void ABCharacter::EquipRifleParts()
{
	ABPlayerState* BPlayerState = GetBPlayerState();
	if (!BPlayerState)
	{
		UE_LOG(LogTemp, Warning, TEXT("í”Œë ˆì´ì–´ ìƒíƒœë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
		return;
	}

	// RiflePart í´ë˜ìŠ¤ë¡œ ì¸ë²¤í† ë¦¬ ê²€ìƒ‰
	TArray<FItemData> RiflePartsInInventory = BPlayerState->GetInventoryClassItem(ABRiflePart::StaticClass());
	UE_LOG(LogTemp, Log, TEXT("Found %d RiflePart items in inventory."), RiflePartsInInventory.Num());

	// ì¥ì°© í›„ ì œê±°í•  ì•„ì´í…œ ëª©ë¡
	TArray<FItemData> ItemsToRemove;

	for (const FItemData& RiflePartItem : RiflePartsInInventory)
	{
		if (RiflePartItem.ItemClass)
		{
			// ItemClassì—ì„œ RiflePart ê°ì²´ ìƒì„±
			ABRiflePart* RiflePart = NewObject<ABRiflePart>(this, RiflePartItem.ItemClass);

			if (RiflePart)
			{
				UE_LOG(LogTemp, Log, TEXT("Attempting to apply RiflePart: %s"), *RiflePart->PartName);

				// RiflePartë¥¼ ë¼ì´í”Œì— ì¥ì°©
				RiflePart->UseItem(this);

				// ì œê±°í•  ì•„ì´í…œ ëª©ë¡ì— ì¶”ê°€ (ë°”ë¡œ ì‚­ì œí•˜ë©´ ì•ˆ ë¨)
				ItemsToRemove.Add(RiflePartItem);

				UE_LOG(LogTemp, Log, TEXT("%s íŒŒì¸ ê°€ ë¼ì´í”Œì— ì¥ì°©ë˜ì—ˆìŠµë‹ˆë‹¤."), *RiflePart->PartName);
				
				
			}
			else
			{
				UE_LOG(LogTemp, Warning, TEXT("ë¼ì´í”Œ íŒŒì¸ ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
			}
		}
	}

	// ğŸ”¹ ëª¨ë“  ì•„ì´í…œì„ ë£¨í”„ê°€ ëë‚œ í›„ ì‚­ì œ
	for (const FItemData& Item : ItemsToRemove)
	{
		BPlayerState->InventoryRemoveItem(Item);
	}
	
}

void ABCharacter::EquipPistolParts()
{
	ABPlayerState* BPlayerState = GetBPlayerState();
	if (!BPlayerState)
	{
		UE_LOG(LogTemp, Warning, TEXT("í”Œë ˆì´ì–´ ìƒíƒœë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
		return;
	}

	// PistolPart í´ë˜ìŠ¤ë¡œ ì¸ë²¤í† ë¦¬ ê²€ìƒ‰
	TArray<FItemData> PistolPartsInInventory = BPlayerState->GetInventoryClassItem(ABPistolPart::StaticClass());
	UE_LOG(LogTemp, Log, TEXT("Found %d PistolPart items in inventory."), PistolPartsInInventory.Num());

	// ì¥ì°© í›„ ì œê±°í•  ì•„ì´í…œ ëª©ë¡
	TArray<FItemData> ItemsToRemove;

	for (const FItemData& PistolPartItem : PistolPartsInInventory)
	{
		if (PistolPartItem.ItemClass)
		{
			// ItemClassì—ì„œ PistolPart ê°ì²´ ìƒì„±
			ABPistolPart* PistolPart = NewObject<ABPistolPart>(this, PistolPartItem.ItemClass);

			if (PistolPart)
			{
				UE_LOG(LogTemp, Log, TEXT("Attempting to apply PistolPart: %s"), *PistolPart->PartName);

				// PistolPartë¥¼ í”¼ìŠ¤í†¨ì— ì¥ì°©
				PistolPart->UseItem(this);

				// ì œê±°í•  ì•„ì´í…œ ëª©ë¡ì— ì¶”ê°€
				ItemsToRemove.Add(PistolPartItem);

				UE_LOG(LogTemp, Log, TEXT("%s íŒŒì¸ ê°€ í”¼ìŠ¤í†¨ì— ì¥ì°©ë˜ì—ˆìŠµë‹ˆë‹¤."), *PistolPart->PartName);
			}
			else
			{
				UE_LOG(LogTemp, Warning, TEXT("í”¼ìŠ¤í†¨ íŒŒì¸ ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
			}
		}
	}

	// ğŸ”¹ ë£¨í”„ ì¢…ë£Œ í›„ ì•„ì´í…œ ì‚­ì œ
	for (const FItemData& Item : ItemsToRemove)
	{
		BPlayerState->InventoryRemoveItem(Item);
	}
}

void ABCharacter::EquipShotgunParts()
{
	ABPlayerState* BPlayerState = GetBPlayerState();
	if (!BPlayerState)
	{
		UE_LOG(LogTemp, Warning, TEXT("í”Œë ˆì´ì–´ ìƒíƒœë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
		return;
	}

	// ShotgunPart í´ë˜ìŠ¤ë¡œ ì¸ë²¤í† ë¦¬ ê²€ìƒ‰
	TArray<FItemData> ShotgunPartsInInventory = BPlayerState->GetInventoryClassItem(ABShotgunPart::StaticClass());
	UE_LOG(LogTemp, Log, TEXT("Found %d ShotgunPart items in inventory."), ShotgunPartsInInventory.Num());

	// ì¥ì°© í›„ ì œê±°í•  ì•„ì´í…œ ëª©ë¡
	TArray<FItemData> ItemsToRemove;

	for (const FItemData& ShotgunPartItem : ShotgunPartsInInventory)
	{
		if (ShotgunPartItem.ItemClass)
		{
			// ItemClassì—ì„œ ShotgunPart ê°ì²´ ìƒì„±
			ABShotgunPart* ShotgunPart = NewObject<ABShotgunPart>(this, ShotgunPartItem.ItemClass);

			if (ShotgunPart)
			{
				UE_LOG(LogTemp, Log, TEXT("Attempting to apply ShotgunPart: %s"), *ShotgunPart->PartName);

				// ShotgunPartë¥¼ ìƒ·ê±´ì— ì¥ì°©
				ShotgunPart->UseItem(this);

				// ì œê±°í•  ì•„ì´í…œ ëª©ë¡ì— ì¶”ê°€
				ItemsToRemove.Add(ShotgunPartItem);

				UE_LOG(LogTemp, Log, TEXT("%s íŒŒì¸ ê°€ ìƒ·ê±´ì— ì¥ì°©ë˜ì—ˆìŠµë‹ˆë‹¤."), *ShotgunPart->PartName);
			}
			else
			{
				UE_LOG(LogTemp, Warning, TEXT("ìƒ·ê±´ íŒŒì¸ ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
			}
		}
	}

	// ğŸ”¹ ë£¨í”„ ì¢…ë£Œ í›„ ì•„ì´í…œ ì‚­ì œ
	for (const FItemData& Item : ItemsToRemove)
	{
		BPlayerState->InventoryRemoveItem(Item);
	}
}

void ABCharacter::InventorySwitch()
{
	static bool Switch = false;

	if (!Switch)
	{
		ShowInventory();
	}
	else
	{
		CloseInventory();
	}
	Switch = !Switch;
}

void ABCharacter::UseItem(const FName& ItemName)
{
	State->UseItem(ItemName);
}


void ABCharacter::EquipPistol()
{
	UE_LOG(LogTemp, Warning, TEXT("EquipPistol() called!"));
	ActiveWeaponSlot = EWeaponSlot::Pistol;
	EquipWeaponByType(ActiveWeaponSlot);
}

void ABCharacter::EquipRifle()
{
	UE_LOG(LogTemp, Warning, TEXT("EquipRifle() called!"));
	ActiveWeaponSlot = EWeaponSlot::Rifle;
	EquipWeaponByType(ActiveWeaponSlot);
}

void ABCharacter::EquipShotgun()
{
	UE_LOG(LogTemp, Warning, TEXT("EquipShotgun() called!"));
	ActiveWeaponSlot = EWeaponSlot::ShotGun;
	EquipWeaponByType(ActiveWeaponSlot);
}

void ABCharacter::EquipMelee()
{
	UE_LOG(LogTemp, Warning, TEXT("EquipMelee() called!"));
	ActiveWeaponSlot = EWeaponSlot::Melee;
	EquipWeaponByType(ActiveWeaponSlot);
}
void ABCharacter::EquipGrenade()
{
	UE_LOG(LogTemp, Warning, TEXT("EquipGrenade() called!"));
	ActiveWeaponSlot = EWeaponSlot::Throwable;
	EquipWeaponByType(ActiveWeaponSlot);
}
void ABCharacter::UseFirstAidKit()
{
	// í”Œë ˆì´ì–´ ìƒíƒœ í™•ì¸
	ABPlayerState* BPlayerState = GetBPlayerState();
	if (!BPlayerState)
	{
		UE_LOG(LogTemp, Warning, TEXT("í”Œë ˆì´ì–´ ìƒíƒœë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤. ì¹˜ë£Œ ì•„ì´í…œ ì‚¬ìš© ë¶ˆê°€"));
		return;
	}

	// ğŸ”¹ ì¸ë²¤í† ë¦¬ì—ì„œ êµ¬ê¸‰ìƒì ì°¾ê¸°
	FName HealingItemName = "FirstAidKit";  // ì•„ì´í…œ ì´ë¦„
	TArray<FItemData> HealingItems = BPlayerState->GetInventoryTypeItem(HealingItemName);

	if (HealingItems.Num() > 0)
	{
		// ì²« ë²ˆì§¸ êµ¬ê¸‰ìƒì ì•„ì´í…œì„ ì‚¬ìš©
		ABBaseItem* HealingItem = HealingItems[0].ItemRef;
		if (HealingItem)
		{
			HealingItem->UseItem(this);  // ì•„ì´í…œ ì‚¬ìš© (ì²´ë ¥ íšŒë³µ)

			// âœ… ì²´ë ¥ íšŒë³µ í›„ ë¡œê·¸ ì¶œë ¥
			UE_LOG(LogTemp, Log, TEXT("êµ¬ê¸‰ìƒì ì‚¬ìš© ì™„ë£Œ. í˜„ì¬ ì²´ë ¥: %f"),BPlayerState -> GetCurrentHealth());
		}
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("êµ¬ê¸‰ìƒìê°€ ì—†ìŠµë‹ˆë‹¤!"));
	}
}
TArray<ABBaseItem*> ABCharacter::GetNearItemArray() const
{
	TArray<AActor*> ActivateItem;
	TArray<ABBaseItem*> BaseItem;

	CollectNearItem->GetOverlappingActors(ActivateItem);

	for (AActor* Actor : ActivateItem)
	{
		if (ABBaseItem* Base = Cast<ABBaseItem>(Actor))
		{
			BaseItem.Add(Base);
		}
	}
	return BaseItem;
}

void ABCharacter::ShowInventory()
{
	if (UBGameInstance* Instance = Cast<UBGameInstance>(GetGameInstance()))
	{
		if (UBUIManager* UIManager = Cast<UBUIManager>(Instance->GetUIManagerInstance()))
		{
			UIManager->ShowInventory();
			if (UBInventoryWidget* Inventory = Cast<UBInventoryWidget>(UIManager->GetInventoryInstance()))
			{
				Inventory->SendItemData(GetNearItemArray(), Cast<ABPlayerState>(GetPlayerState()));
			}
		}
	}
}

void ABCharacter::CloseInventory()
{
	if (UBGameInstance* Instance = Cast<UBGameInstance>(GetGameInstance()))
	{
		if (UBUIManager* UIManager = Cast<UBUIManager>(Instance->GetUIManagerInstance()))
		{
			UIManager->CloseInventory();
		}
	}
}

float ABCharacter::TakeDamage(float DamageAmount, FDamageEvent const& DamageEvent, AController* EventInstigator, AActor* DamageCauser)
{
	float ActualDamage = Super::TakeDamage(DamageAmount, DamageEvent, EventInstigator, DamageCauser);

	GEngine->AddOnScreenDebugMessage(-1, 2.f, FColor::Magenta, FString::Printf(TEXT("TakeDamage ActualDamage %d"), ActualDamage));
	GEngine->AddOnScreenDebugMessage(-1, 2.f, FColor::Magenta, FString::Printf(TEXT("TakeDamage DamageAmount %d"), DamageAmount));

	if (ABPlayerState* BPlayerState = GetPlayerState<ABPlayerState>())
	{
		BPlayerState->AddCurrentHealth(-DamageAmount);
		if (BPlayerState->GetCurrentHealth() <= 0)
		{
			BPlayerState->StartDeath();
		}
	}

	return ActualDamage;
}


void ABCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	UEnhancedInputComponent* EnhancedInput = Cast<UEnhancedInputComponent>(PlayerInputComponent);
	if (EnhancedInput == nullptr)
	{
		return;
	}
	ABPlayerController* PlayerController = Cast<ABPlayerController>(GetController());
	if (PlayerController == nullptr)
	{
		return;
	}

	EnhancedInput->BindAction(
		PlayerController->MoveAction,
		ETriggerEvent::Triggered,
		this,
		&ABCharacter::Move);
	EnhancedInput->BindAction(
		PlayerController->SprintAction,
		ETriggerEvent::Triggered,
		this,
		&ABCharacter::StartSprint);
	EnhancedInput->BindAction(
		PlayerController->SprintAction,
		ETriggerEvent::Completed,
		this,
		&ABCharacter::StopSprint);

	EnhancedInput->BindAction(
		PlayerController->LookAction,
		ETriggerEvent::Triggered,
		this,
		&ABCharacter::Look);

	EnhancedInput->BindAction(
		PlayerController->JumpAction,
		ETriggerEvent::Triggered,
		this,
		&ABCharacter::StartJump);
	EnhancedInput->BindAction(
		PlayerController->JumpAction,
		ETriggerEvent::Completed,
		this,
		&ABCharacter::StopJump);
	EnhancedInput->BindAction(
		PlayerController->AttackAction,
		ETriggerEvent::Triggered,
		this,
		&ABCharacter::Attack
	);
	EnhancedInput->BindAction(
		PlayerController->ReloadAction,
		ETriggerEvent::Completed,
		this,
		&ABCharacter::Reload);

	EnhancedInput->BindAction(
		PlayerController->EquipPistolAction,
		ETriggerEvent::Completed,  // ğŸ”¹ í‚¤ë¥¼ ëˆ„ë¥´ëŠ” ìˆœê°„ ì‹¤í–‰ë˜ë„ë¡ ë³€ê²½
		this,
		&ABCharacter::EquipPistol);
	EnhancedInput->BindAction(
		PlayerController->EquipRifleAction,
		ETriggerEvent::Completed,  // ğŸ”¹ í‚¤ë¥¼ ëˆ„ë¥´ëŠ” ìˆœê°„ ì‹¤í–‰
		this,
		&ABCharacter::EquipRifle);
	EnhancedInput->BindAction(
		PlayerController->EquipShotgunAction,
		ETriggerEvent::Completed,  // ğŸ”¹ í‚¤ë¥¼ ëˆ„ë¥´ëŠ” ìˆœê°„ ì‹¤í–‰
		this,
		&ABCharacter::EquipShotgun);
	EnhancedInput->BindAction(
		PlayerController->EquipMeleeAction,
		ETriggerEvent::Completed,  // ğŸ”¹ í‚¤ë¥¼ ëˆ„ë¥´ëŠ” ìˆœê°„ ì‹¤í–‰
		this,
		&ABCharacter::EquipMelee);
	EnhancedInput->BindAction(
		PlayerController->EquipGrenadeAction,
		ETriggerEvent::Completed,  // ğŸ”¹ í‚¤ë¥¼ ëˆ„ë¥´ëŠ” ìˆœê°„ ì‹¤í–‰
		this,
		&ABCharacter::EquipGrenade);
	EnhancedInput->BindAction(
		PlayerController->UseFristAidKitAction,
		ETriggerEvent::Completed,  // ğŸ”¹ í‚¤ë¥¼ ëˆ„ë¥´ëŠ” ìˆœê°„ ì‹¤í–‰
		this,
		&ABCharacter::UseFirstAidKit);
	EnhancedInput->BindAction(
		PlayerController->ZoomAction,
		ETriggerEvent::Triggered,
		this,
		&ABCharacter::ZoomStart);
	EnhancedInput->BindAction(
		PlayerController->ZoomAction,
		ETriggerEvent::Completed,
		this,
		&ABCharacter::ZoomStop);
}
