#include "BProjectileBase.h"
#include "Components/SphereComponent.h"
#include "Components/DecalComponent.h"
#include "Components/AudioComponent.h"
#include "Kismet/GameplayStatics.h"

ABProjectileBase::ABProjectileBase()
{
    PrimaryActorTick.bCanEverTick = true;

    // âœ… ì¶©ëŒ ì»´í¬ë„ŒíŠ¸ ì¶”ê°€ (ì´ì•Œ í¬ê¸° ì¡°ì •)
    CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionComponent"));
    CollisionComponent->InitSphereRadius(5.0f);  // ì¶©ëŒ ë²”ìœ„ ì„¤ì •
    CollisionComponent->SetCollisionProfileName(TEXT("Projectile"));  // ì¶©ëŒ í”„ë¡œí•„ ì„¤ì •
    CollisionComponent->OnComponentHit.AddDynamic(this, &ABProjectileBase::OnHit);  // ì¶©ëŒ ì´ë²¤íŠ¸ ì—°ê²°
    RootComponent = CollisionComponent;

    // âœ… ì´ì•Œ ë©”ì‹œ ì¶”ê°€
    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
    MeshComponent->SetupAttachment(CollisionComponent);
    MeshComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision); // âœ… ì¶©ëŒ ë¹„í™œì„±í™” (ì¶©ëŒì€ CollisionComponentê°€ ë‹´ë‹¹)
    // âœ… ì´ì•Œ ì´ë™ ì»´í¬ë„ŒíŠ¸ ì¶”ê°€
    ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovement"));
    ProjectileMovement->UpdatedComponent = CollisionComponent;
    ProjectileMovement->InitialSpeed = 3000.0f;  // ì´ˆê¸° ì†ë„ (ì¶©ë¶„íˆ ì»¤ì•¼ í•¨)
    ProjectileMovement->MaxSpeed = 5000.0f;
    ProjectileMovement->bShouldBounce = true;
    ProjectileMovement->bSimulationEnabled = true;
    ProjectileMovement->bSweepCollision = true;  // âœ… ì¶©ëŒ ê°ì§€ í™œì„±í™”
    // ğŸ”¹ ë°œì‚¬ì²´ë¼ë¦¬ ì¶©ëŒí•˜ì§€ ì•Šë„ë¡ ì„¤ì •
    if (CollisionComponent)
    {
        CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
        CollisionComponent->SetCollisionObjectType(ECC_PhysicsBody);
        CollisionComponent->SetCollisionResponseToAllChannels(ECR_Block);
        CollisionComponent->SetCollisionResponseToChannel(ECC_PhysicsBody, ECR_Ignore);  // ë‹¤ë¥¸ íƒ„í™˜ê³¼ ì¶©ëŒ ë°©ì§€
        // âœ… ìºë¦­í„°(Pawn)ì™€ ì¶©ëŒ ë¬´ì‹œ
        CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Ignore);
    }

    // ğŸ”¹ íƒ„í™˜ë¼ë¦¬ ì„œë¡œ ì¶©ëŒí•˜ì§€ ì•Šë„ë¡ ì„¤ì •
    TArray<AActor*> IgnoreActors;
    GetAttachedActors(IgnoreActors);
    for (AActor* IgnoredActor : IgnoreActors)
    {
        CollisionComponent->IgnoreActorWhenMoving(IgnoredActor, true);
    }
}

void ABProjectileBase::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit)
{
    UE_LOG(LogTemp, Warning, TEXT("ABProjectileBase::OnHit Called! Actors: %s"), *OtherActor->GetName());
    if (OtherActor && OtherActor != this && OtherComp)
    {
        UE_LOG(LogTemp, Warning, TEXT("Hit Actor: %s"), *OtherActor->GetName());
        UE_LOG(LogTemp, Warning, TEXT("Hit Location: %s"), *GetActorLocation().ToString());
    }
    if (OtherActor && OtherActor != this && OtherComp)
    {
        // âœ… ë°ë¯¸ì§€ ì ìš©
        UGameplayStatics::ApplyDamage(OtherActor, Damage, GetInstigatorController(), this, UDamageType::StaticClass());

        // âœ… íƒ„í” ë°ì¹¼ ìƒì„±
        UMaterialInterface* BulletDecalMaterial = LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/KSH/Asset/Bullet/M_BulletHole.M_BulletHole"));
        if (BulletDecalMaterial)
        {
            FVector DecalSize = FVector(5.0f, 5.0f, 5.0f);  // í¬ê¸° ì¡°ì •
            UGameplayStatics::SpawnDecalAtLocation(GetWorld(), BulletDecalMaterial, DecalSize,
                Hit.ImpactPoint, Hit.ImpactNormal.Rotation(), 10.0f);
            UDecalComponent* BulletDecal = UGameplayStatics::SpawnDecalAtLocation(
                GetWorld(), BulletDecalMaterial, FVector(5.0f, 5.0f, 5.0f),
                Hit.ImpactPoint, Hit.ImpactNormal.Rotation(), 10.0f
            );
            if (BulletDecal)
            {
                BulletDecal->SetFadeScreenSize(0.01f); // í™”ë©´ ë©€ì–´ì§€ë©´ ìë™ ì œê±°
                BulletDecal->SetFadeOut(5.0f, 1.0f);  // 5ì´ˆ í›„ì— 1ì´ˆ ë™ì•ˆ ì„œì„œíˆ ì‚¬ë¼ì§
            }
        }
        // âœ… ì¶©ëŒí•œ í‘œë©´ì˜ Physical Material ê°€ì ¸ì˜¤ê¸°
        UPhysicalMaterial* PhysMaterial = Hit.PhysMaterial.IsValid() ? Hit.PhysMaterial.Get() : nullptr;
        float SurfaceValue = 0.0f;  // ê¸°ë³¸ê°’
        
        if (PhysMaterial)
        {
            // âœ… Surface Type í™•ì¸
            EPhysicalSurface SurfaceType = UPhysicalMaterial::DetermineSurfaceType(PhysMaterial);
            FString MaterialName = PhysMaterial->GetName();

            switch (SurfaceType)
            {
            case EPhysicalSurface::SurfaceType1:  // ê¸ˆì† í‘œë©´
                SurfaceValue = 0.0f;
                break;
            case EPhysicalSurface::SurfaceType2:  // ë°”ë‹¥ í‘œë©´
                SurfaceValue = 1.0f;
                break;
            case EPhysicalSurface::SurfaceType3:  // ë‚˜ë¬´ í‘œë©´
                SurfaceValue = 2.0f;
                break;
            case EPhysicalSurface::SurfaceType4:  // ì½˜í¬ë¦¬íŠ¸ í‘œë©´
                SurfaceValue = 3.0f;
                break;
            case EPhysicalSurface::SurfaceType5:  // ì  í‘œë©´
                SurfaceValue = 4.0f;
                break;
            default:
                SurfaceValue = 0.0f;
                break;
            }
        }
        

        // âœ… ì˜¤ë””ì˜¤ ì»´í¬ë„ŒíŠ¸ë¥¼ ìƒì„±í•˜ì—¬ ì‚¬ìš´ë“œ ì¬ìƒ ë° íŒŒë¼ë¯¸í„° ì ìš©
        if (HitSoundCue)
        {
            UAudioComponent* AudioComponent = UGameplayStatics::SpawnSoundAtLocation(
                GetWorld(),
                HitSoundCue,
                Hit.ImpactPoint
            );

            if (AudioComponent)
            {

                // âœ… ì‚¬ìš´ë“œ íì˜ íŒŒë¼ë¯¸í„° ì ìš© (Int & Float ëª¨ë‘ ì„¤ì •)
                AudioComponent->SetIntParameter(TEXT("SurfaceValue"), (int32)SurfaceValue);
                AudioComponent->SetFloatParameter(TEXT("SurfaceValue"), SurfaceValue);
                // âœ… ì‚¬ìš´ë“œ ì¬ìƒ ì‹œì‘
                AudioComponent->Play();

            }
            if (AActor* HitActor = Hit.GetActor())
            {
                APawn* NoiseInstigator = Cast<APawn>(HitActor);
                if (NoiseInstigator)
                {
                    MakeNoise(1.0f, NoiseInstigator, Hit.ImpactPoint);
                }
            }
        }
        if (ParticleSystem && HitComp)
        {
            // HitCompì˜ ìœ„ì¹˜ë¥¼ ì‚¬ìš©í•´ì„œ íŒŒí‹°í´ì„ ìƒì„±
            UParticleSystemComponent* ParticleComp = UGameplayStatics::SpawnEmitterAtLocation(
                GetWorld(),                // í˜„ì¬ ì›”ë“œ
                ParticleSystem,            // ì‚¬ìš©í•  íŒŒí‹°í´ ì‹œìŠ¤í…œ
                HitComp->GetComponentLocation(), // HitCompì˜ ìœ„ì¹˜
                FRotator::ZeroRotator,     // íšŒì „ (í•„ìš”ì— ë”°ë¼ ì¡°ì •)
                true                        // íŒŒí‹°í´ì˜ ì›”ë“œ ìœ„ì¹˜ ì‚¬ìš© ì—¬ë¶€
            );
        }
        // âœ… ì´ì•Œ ì œê±°
        Destroy();

    }
}

// âœ… ë°©í–¥ ì„¤ì • (ë°œì‚¬)
void ABProjectileBase::FireInDirection(const FVector& ShootDirection)
{
    // ğŸ”¹ ë°œì‚¬ìì˜ ì¶©ëŒ ë¬´ì‹œ ì„¤ì •
    if (GetOwner())
    {
        AActor* OwnerActor = GetOwner();
        if (CollisionComponent)
        {
            CollisionComponent->IgnoreActorWhenMoving(OwnerActor, true);
        }
    }
    if (ProjectileMovement)
    {
        ProjectileMovement->Velocity = ShootDirection * ProjectileMovement->InitialSpeed;
    }
    
}

